name: EpicFreedomMod
main: me.StevenLawson.TotalFreedomMod.TotalFreedomMod
version: 4.0
description: Plugin for the EpicFreedom server.
softdepend: [BukkitTelnet, DisguiseCraft, WorldEdit, Essentials]
authors: [Madgeek1450, Prozza]

# plugin.yml is no longer used to define commands.
